#!/bin/sh

#get the value of a color from the current xrdb load configuration
getXresColor() {
echo -n "$( xrdb -query | grep "\*$1:" | grep -oE "#[a-zA-Z0-9]{6}" | cut -c 2- )";
}

# Fonts defined in xfontsel (xft not yet supported)
FONT1="-*-stlarch-medium-r-normal-*-10-100-75-75-c-80-iso10646-1"
#FONT2="-*-tewi-medium-*-*-*-*-*-*-*-*-*-*-*"
#FONT2="-*-lemon-medium-*-*-*-10-110-*-*-m-*-*-*"
#FONT2="-*-creep-*-*-*-*-*-*-*-*-*-*-*-*"
FONT2="-*-dweep-*-*-*-*-*-*-*-*-*-*-*-*"
#FONT2="-*-gohufont-medium-*-*-*-11-*-*-*-*-*-iso10646-*"
#FONT2="-*-creep-*-*-*-*-0-*-*-*-*-*-*-*"
FONT3="-misc-fixed-medium-r-normal-ja-0-0-75-75-c-0-iso10646-1"

COLOR_BACKGROUND="#ff$(getXresColor background)"
COLOR_FOREGROUND="#ff$(getXresColor color15)"
COLOR_ICON="#ff$(getXresColor color4)"
COLOR_ACTIVE="#ff$(getXresColor color4)"
COLOR_OCCUPIED="#FF$(getXresColor color8)"
COLOR_URGENT="#FF$(getXresColor color1)"

# Height of underlines / overlines
LINEHEIGHT="3"

# Panel geometry
PANEL_HEIGHT=15
PANEL_WIDTH=''
PANEL_GAP=8
PANEL_GEOMETRY="${PANEL_WIDTH}x${PANEL_HEIGHT}+0+0"

# Notification geometry
NOTIFY_HEIGHT=$PANEL_HEIGHT
NOTIFY_WIDTH=135
NOTIFY_GEOMETRY="${NOTIFY_WIDTH}x${NOTIFY_HEIGHT}+0+0"

# Duration of notifications
DURATION=1

# Monitor to display panel on
MONITOR="$(bspc query -M | tail -n1)"

# W-Fi
WIFI=wlp3s0

# Volume change clip
CLIP="/usr/share/sounds/freedesktop/stereo/audio-volume-change.oga"
# Length of volume bar
BAR_LENGTH=20
BAR_CHAR='='

