#!/bin/sh

# Colors for reference, from base16
#*.foreground:   base05
#*.background:   base00
#*.cursorColor:  base05

#*.color0:       base00
#*.color1:       base08
#*.color2:       base0B
#*.color3:       base0A
#*.color4:       base0D
#*.color5:       base0E
#*.color6:       base0C
#*.color7:       base05

#*.color8:       base03
#*.color9:       base09
#*.color10:      base01
#*.color11:      base02
#*.color12:      base04
#*.color13:      base06
#*.color14:      base0F
#*.color15:      base07

#get the value of a color from the current xrdb load configuration
getXresColor() {
echo -n "$( xrdb -query | grep "\*$1:" | grep -oE "#[a-zA-Z0-9]{6}" | cut -c 2- )";
}

# Fonts defined in xfontsel (xft not yet supported)
FONT1="-*-stlarch-medium-r-normal-*-10-100-75-75-c-80-iso10646-1"
FONT2="-*-dweep-medium-r-semicondensed-*-11-*-*-*-*-*-*-*"
FONT3="-misc-fixed-medium-r-normal-ja-0-0-75-75-c-0-iso10646-1"

COLOR_BACKGROUND="#ff$(getXresColor background)"
COLOR_FOREGROUND="#ff$(getXresColor foreground)"
COLOR_ICON="#ff$(getXresColor color4)"
COLOR_ACTIVE="#ff$(getXresColor color4)"
COLOR_OCCUPIED="#FF$(getXresColor color8)"
COLOR_URGENT="#FF$(getXresColor color1)"

# Height of underlines / overlines
LINEHEIGHT="3"

# Panel geometry
PANEL_HEIGHT=18
PANEL_WIDTH=''
PANEL_GAP=8
PANEL_GEOMETRY="${PANEL_WIDTH}x${PANEL_HEIGHT}+0+0"

# Notification geometry
NOTIFY_HEIGHT=$PANEL_HEIGHT
NOTIFY_WIDTH=135
NOTIFY_GEOMETRY="${NOTIFY_WIDTH}x${NOTIFY_HEIGHT}+0+0"

# Duration of notifications
DURATION=1

# Monitor to display panel on
MONITOR="$(bspc query -M | tail -n1)"

# W-Fi
WIFI=wlp3s0b1

# Volume change clip
CLIP="/usr/share/sounds/freedesktop/stereo/audio-volume-change.oga"
# Length of volume bar
BAR_LENGTH=20
BAR_CHAR='='

