#!/bin/bash
source $(dirname $0)/config

# BATTERY ICONS:
#      

BAT=`acpi -b | awk '{gsub(/%,/,""); print $4}' | sed 's/%//g'`
STATUS=`acpi -b | awk '{gsub(/,/,""); print $3}'`

# Set Icon
icon=""
if [[ $STATUS != "Discharging" ]]; then
	icon=""
elif [[ $BAT -lt 10 ]]; then
	icon=""
elif [[ $BAT -lt 40 ]]; then
	icon=""
elif [[ $BAT -lt 70 ]]; then
	icon=""
else
	icon=""
fi
s="«"

# Create Bar
echo "%{F$COLOR_ICON}$icon%{F-} "

