#!/bin/sh
getXresColor() {
echo -n "$( xrdb -query | grep "\*$1:" | grep -oE "#[a-zA-Z0-9]{6}" | cut -c 2- )";
}

SCREENWIDTH=$(bspc query -T -m | head -n 1 | awk -F"+" '{print $1}' | awk -F"x" '{print $1}')
SCREENHEIGHT=$(bspc query -T -m | head -n 1 | awk -F"+" '{print $1}' | awk -F"x" '{print $2}')

EDGEWIDTH=50
DMENUWIDTH=$SCREENWIDTH

XPOS=0
YPOS=15

FGSELECT="#$(getXresColor foreground)"
BGSELECT="#$(getXresColor color4)"
BG="#$(getXresColor background)"
FG="#$(getXresColor foreground)"
FONT="-*-Lemon-*-*-*-*-*-*-*-*-*-*-*-*"

dmenu_run -w $DMENUWIDTH \
  -x $XPOS \
  -y $YPOS \
  -fn ${FONT} \
  -nb $BG \
  -nf $FG \
  -sb $BGSELECT \
  -p ">"
