# Powerline
run-shell "powerline-daemon -q"
source "/usr/local/lib/python2.7/site-packages/powerline/bindings/tmux/powerline.conf"

set -g prefix C-a
unbind-key C-b
bind-key C-a send-prefix

#set-option -g default-command "reattach-to-user-namespace -l fish"
set -s escape-time 0

set -g mouse on

bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

bind h select-pane -L
bind l select-pane -R
bind k select-pane -U
bind j select-pane -D

bind r source-file ~/.tmux.conf

set-option -g  default-terminal 'screen-256color'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'mattdavis90/base16-tmux'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

run '~/.tmux/plugins/tpm/tpm'

#set -g window-status-format '#I:#(pwd="#{pane_current_path}"; echo ${pwd####*/})#F'
#set -g window-status-current-format '#I:#(pwd="#{pane_current_path}"; echo ${pwd####*/})#F'

## status bar updates every 15s by default**, change to 1s here 
## (this step is optional - a lower latency might have negative battery/cpu usage impacts)
#set -g status-interval 1
